function cntrl=controlsGUI(inrev)
%Cotrols are in a cell, each row has Name, Label, and type
%   Retrurns a cell of control and default data for the controls using the
%   instrument structure
    switch nargin
        case 0,
            rev=1;
        otherwise
            rev=inrev;
    end


    switch rev
        case 1
%        Control Name     Control Label    Control Type     Row Index
cntrl={ 'Pin',              'Pin',              4,          1;...
        'Active',           'Status',           9,          1;...
        'Mode',             'Mode',             2,          2;...
        'Trigger',          'Trig',             2,          3;...
        'Auto',             'Auto',             2,          4;...
        'Monitor',          'Monitor',          2,          5;...
        'Sync1',            'Sync 1',           2,          6;...    
        'Sync2',            'Sync 2',           2,          7;...
        'PeriodOrFreq',     'Rates',            2,          8;...
        'TrainType',        'Train Typ',       2,          9;...
        'TrainDelay',       'Train Dly',      3,      	10;...
        'TrainDur',         'Train Dur',      3,      	11;...
        'TrainPeriod',      'Train Per',     3,      	12;...
        'TrainFrequency',   'Train Frq',        3,          13;...
        'TrainQuantity',    'Train Qty',     4,          14;...
        'TrainLevel',       'Train Lev',      5,      	15;...
        'OffsetOrHold',     'H/O',              2,      	16;...
        'EventID',          'EVNT',             2,      	17;...
        'LibID',            'LIB',              2,      	18;...
        'EventType',        'Event Typ',       2,      	19;...
        'EventQuantity',    'Event Qty',        4,          20;...
        'EventDelay',       'Event Dly',        3,          21;...
        'EventDur1',        'Event Dr1',        3,          22;...
        'EventDur2',        'Event Int',        3,          23;...
        'EventDur3',        'Event Dr2',        3,          24;...
        'EventPeriod',      'Event Prd',        3,          25;...
        'EventFrequency',   'Event Frq',        3,          26;...
        'EventAmp1',        'Event Am1',        5,          27;...
        'EventAmp2',        'Event Am2',        5,          28;...                                        ...
        'EventList',        'Event Lst',       6,          29;...       
        'Ymax',             'Y max',            5,          30;...
        'Ymin',             'Y min',            5,          31; ...
        'menupage',         'Set Inst Page'        2            32;};
  
    end 
end